import type { Metadata } from "next";
import { COMPANY } from "@/lib/legal/company";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of Stemflow.",
};

/*
 * PLACEHOLDER — Replace the [PLACEHOLDER] sections below with real legal text
 * generated by Termly, Stripe Atlas, or legal counsel before going live.
 */

export default function TermsPage() {
  return (
    <>
      <div style={titleBlock}>
        <h1 style={h1}>Terms of Service</h1>
        <p style={meta}>Effective date: {COMPANY.effectiveDate} · {COMPANY.legalName}</p>
      </div>

      <p style={lead}>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the{" "}
        {COMPANY.brandName} platform and services operated by {COMPANY.legalName}{" "}
        (&ldquo;{COMPANY.brandName}&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;). By creating an
        account or using the service, you agree to these Terms. If you do not agree, do not use
        the service.
      </p>

      <Section id="definitions" title="1. Definitions">
        <p>
          <strong>&ldquo;Service&rdquo;</strong> means the {COMPANY.brandName} web application,
          APIs, and related tools available at {COMPANY.appUrl}.
        </p>
        <p>
          <strong>&ldquo;Customer&rdquo;</strong> or <strong>&ldquo;you&rdquo;</strong> means the
          individual or entity that registers for an account and creates an organization.
        </p>
        <p>
          <strong>&ldquo;End Users&rdquo;</strong> means the individuals who interact with
          campaigns you publish using the Service.
        </p>
        {/* [PLACEHOLDER: Add any additional definitions needed for your product] */}
      </Section>

      <Section id="accounts" title="2. Accounts">
        <p>
          You must be at least 18 years old to create an account. You are responsible for
          maintaining the security of your account credentials and for all activity that occurs
          under your account. Notify us immediately at{" "}
          <a href={`mailto:${COMPANY.supportEmail}`} style={inlineLink}>{COMPANY.supportEmail}</a>{" "}
          if you suspect unauthorized access.
        </p>
        {/* [PLACEHOLDER: Add account responsibility clauses specific to your product] */}
      </Section>

      <Section id="acceptable-use" title="3. Acceptable use">
        <p>You agree not to use the Service to:</p>
        <ul style={ul}>
          <li>Violate any applicable law or regulation.</li>
          <li>Collect or process data about individuals without a lawful basis.</li>
          <li>Send spam, unsolicited commercial email, or harassing messages.</li>
          <li>Distribute malware, engage in phishing, or conduct fraudulent activities.</li>
          <li>Circumvent or reverse-engineer any security or access controls.</li>
          <li>Infringe the intellectual property rights of others.</li>
          <li>Resell or sublicense access to the Service without written permission.</li>
        </ul>
        <p>
          We reserve the right to suspend or terminate accounts that violate these terms without
          prior notice.
        </p>
        {/* [PLACEHOLDER: Add product-specific acceptable use clauses] */}
      </Section>

      <Section id="plans-billing" title="4. Plans and billing">
        <p>
          {COMPANY.brandName} offers Free, Pro, and Enterprise plans. Paid plans are billed through
          Stripe. Prices are displayed at checkout and subject to change with 30 days&apos; notice.
        </p>
        <p>
          Subscriptions auto-renew unless cancelled. You may cancel at any time through your billing
          portal; cancellation takes effect at the end of the current billing period. Refunds are
          granted at our discretion for unused time on annual plans.
        </p>
        {/* [PLACEHOLDER: Add specific pricing terms, pro-ration policy, and refund policy] */}
      </Section>

      <Section id="customer-data" title="5. Customer data">
        <p>
          You retain ownership of all data you upload or collect through the Service (&ldquo;Customer
          Data&rdquo;). You grant us a limited license to process Customer Data solely to provide the
          Service. We do not sell or use Customer Data for our own commercial purposes.
        </p>
        <p>
          You represent that you have all necessary rights and consents to collect and process End
          User data through your campaigns, and that doing so complies with applicable privacy laws
          (including GDPR and CCPA where applicable).
        </p>
        {/* [PLACEHOLDER: Add data processing addendum (DPA) reference for GDPR compliance] */}
      </Section>

      <Section id="ip" title="6. Intellectual property">
        <p>
          {COMPANY.brandName} and its licensors own all rights in the Service, including the
          platform software, design, and trademarks. These Terms do not transfer any ownership to
          you. You may not copy, modify, or create derivative works of the Service.
        </p>
        <p>
          You retain all rights to content you create using the Service (campaign pages,
          compositions, audience data).
        </p>
      </Section>

      <Section id="disclaimers" title="7. Disclaimers">
        <p>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTY OF ANY KIND. TO THE FULLEST
          EXTENT PERMITTED BY LAW, {COMPANY.legalName.toUpperCase()} DISCLAIMS ALL WARRANTIES,
          EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
          PURPOSE, AND NON-INFRINGEMENT.
        </p>
        {/* [PLACEHOLDER: Review with counsel for your jurisdiction] */}
      </Section>

      <Section id="limitation" title="8. Limitation of liability">
        <p>
          TO THE FULLEST EXTENT PERMITTED BY LAW, {COMPANY.legalName.toUpperCase()} SHALL NOT BE
          LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY
          LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA,
          USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.
        </p>
        <p>
          OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATING TO THE SERVICE SHALL NOT
          EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.
        </p>
        {/* [PLACEHOLDER: Review with counsel; some jurisdictions do not allow limitations] */}
      </Section>

      <Section id="termination" title="9. Termination">
        <p>
          You may delete your account at any time from account settings. We may suspend or terminate
          your access for material violation of these Terms, with or without notice depending on
          severity.
        </p>
        <p>
          On termination, your right to use the Service ceases. Customer Data is deleted per our
          Privacy Policy retention schedule.
        </p>
      </Section>

      <Section id="governing-law" title="10. Governing law">
        <p>
          These Terms are governed by the laws of the {COMPANY.jurisdiction}, without regard to
          conflict-of-law principles. Any dispute shall be resolved in the courts of the{" "}
          {COMPANY.jurisdiction}.
        </p>
        {/* [PLACEHOLDER: Consider adding arbitration clause and class action waiver] */}
      </Section>

      <Section id="changes" title="11. Changes to these terms">
        <p>
          We may update these Terms from time to time. We will notify you of material changes by
          email or by a notice in the Service at least 14 days before the change takes effect.
          Continued use after the effective date constitutes acceptance of the revised Terms.
        </p>
      </Section>

      <Section id="contact" title="12. Contact">
        <p>
          {COMPANY.legalName}<br />
          {COMPANY.postalAddress}<br />
          <a href={`mailto:${COMPANY.supportEmail}`} style={inlineLink}>{COMPANY.supportEmail}</a>
        </p>
      </Section>
    </>
  );
}

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} style={section}>
      <h2 style={h2}>{title}</h2>
      {children}
    </section>
  );
}

const titleBlock: React.CSSProperties = { marginBottom: "40px" };
const h1: React.CSSProperties = { fontSize: "clamp(26px, 4vw, 36px)", fontWeight: 700, color: "var(--text-primary)", marginBottom: "8px" };
const meta: React.CSSProperties = { fontSize: "13px", color: "var(--text-muted)" };
const lead: React.CSSProperties = { fontSize: "16px", lineHeight: 1.8, color: "var(--text-secondary)", marginBottom: "40px" };
const section: React.CSSProperties = { marginBottom: "40px" };
const h2: React.CSSProperties = { fontSize: "18px", fontWeight: 700, color: "var(--text-primary)", marginBottom: "12px", paddingTop: "8px", borderTop: "1px solid var(--border)" };
const ul: React.CSSProperties = { paddingLeft: "20px", margin: "8px 0", lineHeight: 2 };
const inlineLink: React.CSSProperties = { color: "var(--accent)", textDecoration: "underline" };
