import type { Metadata } from "next";
import { COMPANY } from "@/lib/legal/company";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Stemflow collects, uses, and protects your personal data.",
};

/*
 * PLACEHOLDER — Replace the [PLACEHOLDER] sections below with real policy text
 * generated by Termly, iubenda, or legal counsel before going live.
 * Run a search for "[PLACEHOLDER]" to find every section that needs real content.
 */

export default function PrivacyPage() {
  return (
    <>
      <div style={titleBlock}>
        <h1 style={h1}>Privacy Policy</h1>
        <p style={meta}>Effective date: {COMPANY.effectiveDate} · {COMPANY.legalName}</p>
      </div>

      <p style={lead}>
        {COMPANY.brandName} (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;) operates
        the {COMPANY.brandName} platform at {COMPANY.appUrl}. This Privacy Policy explains what
        personal data we collect, why we collect it, and what rights you have over it.
      </p>

      <Section id="data-we-collect" title="1. Data we collect">
        <p>
          <strong>Account data:</strong> name, email address, hashed password, and email
          verification timestamp when you create an account.
        </p>
        <p>
          <strong>Organization data:</strong> organization name, slug, legal name, and postal
          address you provide in settings.
        </p>
        <p>
          <strong>Billing data:</strong> your subscription plan and Stripe customer/subscription
          IDs. Full payment card details are processed and stored exclusively by Stripe — we never
          see or store raw card numbers.
        </p>
        <p>
          <strong>Campaign audience data:</strong> visitor records that you (as a Stemflow
          customer) collect through your own campaigns. You are the controller of this data; we
          process it on your behalf as a processor.
        </p>
        <p>
          <strong>Usage data:</strong> server logs, IP addresses, user-agent strings, and session
          activity collected automatically for security and rate-limiting purposes.
        </p>
        <p>
          <strong>Media:</strong> files you upload (images, etc.) are stored on Cloudflare R2.
        </p>
        {/* [PLACEHOLDER: Add any additional data types specific to your product] */}
      </Section>

      <Section id="how-we-use" title="2. How we use your data">
        <p>We use your personal data to:</p>
        <ul style={ul}>
          <li>Provide, maintain, and improve the {COMPANY.brandName} platform.</li>
          <li>Send transactional emails (email verification, password reset, team invitations).</li>
          <li>Process payments and manage your subscription via Stripe.</li>
          <li>Enforce rate limits and protect against abuse.</li>
          <li>Respond to support requests.</li>
          <li>Comply with legal obligations.</li>
        </ul>
        <p>
          We do <strong>not</strong> sell your personal data or use it for targeted advertising.
        </p>
        {/* [PLACEHOLDER: Add legal bases under GDPR if applicable (Art. 6)] */}
      </Section>

      <Section id="processors" title="3. Third-party processors">
        <p>
          We share data with the following sub-processors to operate the service. Each is bound by
          appropriate data processing agreements.
        </p>
        <table style={table}>
          <thead>
            <tr>
              <th style={th}>Processor</th>
              <th style={th}>Purpose</th>
              <th style={th}>Location</th>
            </tr>
          </thead>
          <tbody>
            <Processor name="Neon (Neon Inc.)" purpose="PostgreSQL database hosting" location="US" />
            <Processor name="Vercel" purpose="Application hosting, CDN, analytics (cookieless)" location="US" />
            <Processor name="Stripe" purpose="Payment processing and billing" location="US" />
            <Processor name="Resend" purpose="Transactional email delivery" location="US" />
            <Processor name="Cloudflare R2" purpose="Media file storage" location="US / EU" />
            <Processor name="Upstash" purpose="Redis-based rate limiting" location="US" />
          </tbody>
        </table>
        {/* [PLACEHOLDER: Update processor table to match your actual vendors] */}
      </Section>

      <Section id="cookies" title="4. Cookies &amp; tracking">
        <p>
          We use three essential session cookies that are strictly necessary to operate the
          platform. We do <strong>not</strong> use tracking cookies or third-party advertising
          pixels. Vercel Analytics is cookieless and does not identify individual visitors.
        </p>
        <p>
          See our <a href="/cookies" style={inlineLink}>Cookie Policy</a> for a full breakdown.
        </p>
      </Section>

      <Section id="data-retention" title="5. Data retention">
        <p>
          We retain your account data as long as your account is active. If you delete your
          account (see below), we permanently delete your personal data within 30 days, except
          where required to retain it by law (e.g., financial records).
        </p>
        <p>
          Campaign audience data you collected through your campaigns is deleted when you delete
          the campaign or your organization.
        </p>
        {/* [PLACEHOLDER: Specify exact retention periods if required by your jurisdiction] */}
      </Section>

      <Section id="your-rights" title="6. Your rights">
        <p>
          Depending on your location, you may have the right to access, correct, export, or delete
          the personal data we hold about you. {COMPANY.brandName} provides self-service tools for
          all of these:
        </p>
        <ul style={ul}>
          <li>
            <strong>Access &amp; correct</strong> — update your name and email in account settings.
          </li>
          <li>
            <strong>Export</strong> — download a JSON copy of your personal data from account
            settings (Data &amp; Privacy → Export my data).
          </li>
          <li>
            <strong>Delete account</strong> — permanently delete your account and all associated
            data from account settings (Data &amp; Privacy → Delete account). Your organizations,
            campaigns, and audience data are cascade-deleted.
          </li>
          <li>
            <strong>Delete organization</strong> — remove a specific organization and all its
            campaigns from organization settings (Danger Zone → Delete organization).
          </li>
        </ul>
        <p>
          If you need assistance, contact us at{" "}
          <a href={`mailto:${COMPANY.privacyEmail}`} style={inlineLink}>{COMPANY.privacyEmail}</a>.
        </p>
        {/* [PLACEHOLDER: Add GDPR Article 77 supervisory authority info if EU-facing] */}
      </Section>

      <Section id="security" title="7. Security">
        <p>
          We use industry-standard security practices: encrypted session cookies (iron-session),
          bcrypt password hashing, CSRF tokens on all mutating requests, rate limiting, and
          HTTPS-only transport. No system is perfectly secure; if you discover a vulnerability,
          please report it to{" "}
          <a href={`mailto:${COMPANY.supportEmail}`} style={inlineLink}>{COMPANY.supportEmail}</a>.
        </p>
      </Section>

      <Section id="children" title="8. Children">
        <p>
          {COMPANY.brandName} is not directed at children under 13. We do not knowingly collect
          personal data from children. If you believe a child has provided us with personal data,
          contact us at{" "}
          <a href={`mailto:${COMPANY.privacyEmail}`} style={inlineLink}>{COMPANY.privacyEmail}</a>{" "}
          and we will delete it promptly.
        </p>
      </Section>

      <Section id="changes" title="9. Changes to this policy">
        <p>
          We may update this Privacy Policy from time to time. Material changes will be notified
          by email or by a prominent notice in the app. Continued use after notice constitutes
          acceptance of the revised policy.
        </p>
      </Section>

      <Section id="contact" title="10. Contact">
        <p>
          {COMPANY.legalName}<br />
          {COMPANY.postalAddress}<br />
          <a href={`mailto:${COMPANY.privacyEmail}`} style={inlineLink}>{COMPANY.privacyEmail}</a>
        </p>
      </Section>
    </>
  );
}

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} style={section}>
      <h2 style={h2}>{title}</h2>
      {children}
    </section>
  );
}

function Processor({ name, purpose, location }: { name: string; purpose: string; location: string }) {
  return (
    <tr>
      <td style={td}>{name}</td>
      <td style={td}>{purpose}</td>
      <td style={td}>{location}</td>
    </tr>
  );
}

const titleBlock: React.CSSProperties = { marginBottom: "40px" };
const h1: React.CSSProperties = { fontSize: "clamp(26px, 4vw, 36px)", fontWeight: 700, color: "var(--text-primary)", marginBottom: "8px" };
const meta: React.CSSProperties = { fontSize: "13px", color: "var(--text-muted)" };
const lead: React.CSSProperties = { fontSize: "16px", lineHeight: 1.8, color: "var(--text-secondary)", marginBottom: "40px" };
const section: React.CSSProperties = { marginBottom: "40px" };
const h2: React.CSSProperties = { fontSize: "18px", fontWeight: 700, color: "var(--text-primary)", marginBottom: "12px", paddingTop: "8px", borderTop: "1px solid var(--border)" };
const ul: React.CSSProperties = { paddingLeft: "20px", margin: "8px 0", lineHeight: 2 };
const table: React.CSSProperties = { width: "100%", borderCollapse: "collapse", fontSize: "14px", marginTop: "8px" };
const th: React.CSSProperties = { textAlign: "left", padding: "8px 12px", background: "var(--bg-raised)", color: "var(--text-secondary)", fontWeight: 600, fontSize: "12px", borderBottom: "1px solid var(--border)" };
const td: React.CSSProperties = { padding: "8px 12px", borderBottom: "1px solid var(--border)", color: "var(--text-secondary)", fontSize: "13px", verticalAlign: "top" };
const inlineLink: React.CSSProperties = { color: "var(--accent)", textDecoration: "underline" };
